SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE customer_order;
TRUNCATE TABLE order_product;
TRUNCATE TABLE product;
TRUNCATE TABLE product_inventory;
TRUNCATE TABLE customer;
SET FOREIGN_KEY_CHECKS = 1;

DELETE FROM cart;
ALTER TABLE cart AUTO_INCREMENT = 1;

DELETE FROM ORDER_PRODUCT;
ALTER TABLE ORDER_PRODUCT AUTO_INCREMENT = 1;

DELETE FROM CUSTOMER_ORDER;
ALTER TABLE CUSTOMER_ORDER AUTO_INCREMENT = 1;

DELETE FROM product_inventory;
ALTER TABLE product_inventory AUTO_INCREMENT = 1;

DELETE FROM product;
ALTER TABLE product AUTO_INCREMENT = 1;
